# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.utility:
        class: AppBundle\Providers\Utility
        arguments: ["@kernel", "@router", "@session"]
    app.twig_extension:
        class: AppBundle\Extensions\Twig\TwigExtension
        public: false
        tags:
            - { name: twig.extension }
