<?php

namespace AppBundle\Entity\Repository;

/**
 * DemoPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoPersonRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Return all people older than the given age
	 *
	 * @param integer $age the youngest age to return
	 * @return the people if found
	 */
	public function getPeopleOlderThan($age)
	{
		return $this->getEntityManager()
			->createQuery('SELECT p FROM
				AppBundle:DemoPerson p
				WHERE p.age >= :age
				ORDER BY p.name
			')
			->setParameters(array(
				'age' => $age,
			))
			->getResult();
	}
}
